### ISSUE TITLE
Incorrect Error Redirect Url

### ISSUE THREAD

**Issue by wintermute-84** [karliuka/m2.ReCaptcha#10]
Hi,
I'm extending your module to also add recaptcha for a contact form on a product page.

inside `Faonni\ReCaptcha\Observer\ValidateObserver::_redirect()` you are getting redirect url from form url provided in the configs. In my case form url which is also a layout handler is catalog/product/view which is incorrect url when used for redirect.

Wouldn't it be easier to just use a referer in all cases?

```
    protected function _redirect(Action $controller)
    {
		$this->_addError();		
		$this->_redirect->redirect(
			$controller->getResponse(), 
                        $this->_redirect->getRefererUrl()
		);
    }  
```

**Comment by karliuka** [comment]
Hi,
Thank you.
Not all forms can work with referer url. To solve the problem with dynamic URLs, I added your solution.
Use item with name 'referer' for the configuration of your form.

`<item name="referer" xsi:type="boolean">true</item>`

**Comment by wintermute-84** [comment]
Thank you, appreciate it.
