### ISSUE TITLE
Display Error when installed

### ISSUE THREAD

**Issue by shuaiZend** [karliuka/m2.ReCaptcha#11]
1.installed
2.open hompage
3.display:

> Fatal error: Uncaught TypeError: Argument 1 passed to Faonni\ReCaptcha\Model\Form\AbstractFormConfig::__construct() must be of the type array, null given, called in 

ENV:
Magento 2.1.X
Php 7.0.X

**Comment by NikolasSumrak** [comment]
@shuaiZend  Did you run "setup:di:compile" after installation of module?
