### ISSUE TITLE
Override Form Contact Us ReCaptcha not displayed

### ISSUE THREAD

**Issue by vrajeshpatel4u** [karliuka/m2.ReCaptcha#15]
I do override vendor/magento/module-contact/view/frontend/templates/form.phtml with app/design/frontend/my/theme/Magento_Contact/templates/form.phtml. This is the same file with our address and a google map added at the bottom of the page. I'm not sure how the CAPTCHA works but I do not see any mention of CAPTCHA in vendor/magento/module-contact/view/frontend/templates/form.phtml.
When this override file I close with underscore name, recaptcha works well, but not working in override contact us form.

**Comment by karliuka** [comment]
CAPTCHA is output through the section additional.info
module Contact
view/frontend/templates/form.phtml

![screenshot_1](https://user-images.githubusercontent.com/1991955/44845568-90204900-ac56-11e8-8d89-c21d1723edab.png)
