### ISSUE TITLE
bug erreur javascript

### ISSUE THREAD

**Issue by strauss69400** [karliuka/m2.ReCaptcha#3]
Hi,

My website running with the version 2.1.6 of Magento.

After installation and configuration of module, theRecaptcha don't work in frontend i get this problem such as describe in the screenshot :
![image](https://user-images.githubusercontent.com/8798254/26929262-48e1d562-4c59-11e7-91e8-c75366de9ab4.png)

Do you have any idea of how to resolve the problem?
Thanks
Best regards

**Comment by karliuka** [comment]
Sorry, this is not a module bug, it's a bug of the Your custom theme (font integration).
